<?php

use Illuminate\Database\Seeder;

class AccountSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $arr = [
            [
                'account_no' => 'SW14',
                'account_name' => 'ARIEF WIBOWO',
                'cif_no' => NULL,
                'asset_code' => 'IDR',
                'balance' => 0.00,
                'balance_hold' => NULL,
                'equiv_balance' => NULL,
                'account_type' => 'C',
                'is_base' => 'T',
                'compliance_id' => NULL,
                'account_status' => 'A',
                'locked' => NULL,
                'base_account_no' => 'SW14'
            ],
            [
                'account_no' => 'SW18',
                'account_name' => 'RADEN FEB SUMANDAR',
                'cif_no' => NULL,
                'asset_code' => 'IDR',
                'balance' => 0.00,
                'balance_hold' => NULL,
                'equiv_balance' => NULL,
                'account_type' => 'C',
                'is_base' => 'T',
                'compliance_id' => NULL,
                'account_status' => 'A',
                'locked' => NULL,
                'base_account_no' => 'SW18'
            ],
            [
                'account_no' => 'SW55',
                'account_name' => 'ARIES WIDIYATMOKO',
                'cif_no' => NULL,
                'asset_code' => 'IDR',
                'balance' => 0.00,
                'balance_hold' => NULL,
                'equiv_balance' => NULL,
                'account_type' => 'C',
                'is_base' => 'T',
                'compliance_id' => NULL,
                'account_status' => 'A',
                'locked' => NULL,
                'base_account_no' => 'SW55'
            ],
            [
                'account_no' => 'SW82',
                'account_name' => 'NATAL ARGAWAN PARDEDE',
                'cif_no' => NULL,
                'asset_code' => 'IDR',
                'balance' => 0.00,
                'balance_hold' => NULL,
                'equiv_balance' => NULL,
                'account_type' => 'C',
                'is_base' => 'T',
                'compliance_id' => NULL,
                'account_status' => 'A',
                'locked' => NULL,
                'base_account_no' => 'SW82'
            ],
            [
                'account_no' => 'SW24',
                'account_name' => 'ARIF SOETIONO',
                'cif_no' => NULL,
                'asset_code' => 'IDR',
                'balance' => 0.00,
                'balance_hold' => NULL,
                'equiv_balance' => NULL,
                'account_type' => 'C',
                'is_base' => 'T',
                'compliance_id' => NULL,
                'account_status' => 'A',
                'locked' => NULL,
                'base_account_no' => 'SW24'
            ],
            [
                'account_no' => 'SW130',
                'account_name' => 'JONES TJIUNARDI',
                'cif_no' => NULL,
                'asset_code' => 'IDR',
                'balance' => 0.00,
                'balance_hold' => NULL,
                'equiv_balance' => NULL,
                'account_type' => 'C',
                'is_base' => 'T',
                'compliance_id' => NULL,
                'account_status' => 'A',
                'locked' => NULL,
                'base_account_no' => 'SW130'
            ],
            [
                'account_no' => 'SW146',
                'account_name' => 'JOHAN',
                'cif_no' => NULL,
                'asset_code' => 'IDR',
                'balance' => 0.00,
                'balance_hold' => NULL,
                'equiv_balance' => NULL,
                'account_type' => 'C',
                'is_base' => 'T',
                'compliance_id' => NULL,
                'account_status' => 'A',
                'locked' => NULL,
                'base_account_no' => 'SW146'
            ],
            [
                'account_no' => 'SW174',
                'account_name' => 'HANDOKO',
                'cif_no' => NULL,
                'asset_code' => 'IDR',
                'balance' => 0.00,
                'balance_hold' => NULL,
                'equiv_balance' => NULL,
                'account_type' => 'C',
                'is_base' => 'T',
                'compliance_id' => NULL,
                'account_status' => 'A',
                'locked' => NULL,
                'base_account_no' => 'SW174'
            ],
            [
                'account_no' => 'SW187',
                'account_name' => 'YETTI ROCHMANTIWI USADANINGRUM',
                'cif_no' => NULL,
                'asset_code' => 'IDR',
                'balance' => 0.00,
                'balance_hold' => NULL,
                'equiv_balance' => NULL,
                'account_type' => 'C',
                'is_base' => 'T',
                'compliance_id' => NULL,
                'account_status' => 'A',
                'locked' => NULL,
                'base_account_no' => 'SW187'
            ],
            [
                'account_no' => 'SW197',
                'account_name' => 'MOH.REZA',
                'cif_no' => NULL,
                'asset_code' => 'IDR',
                'balance' => 0.00,
                'balance_hold' => NULL,
                'equiv_balance' => NULL,
                'account_type' => 'C',
                'is_base' => 'T',
                'compliance_id' => NULL,
                'account_status' => 'A',
                'locked' => NULL,
                'base_account_no' => 'SW197'
            ],
            [
                'account_no' => 'SW203',
                'account_name' => 'AGUNG LEON HARYATMO',
                'cif_no' => NULL,
                'asset_code' => 'IDR',
                'balance' => 0.00,
                'balance_hold' => NULL,
                'equiv_balance' => NULL,
                'account_type' => 'C',
                'is_base' => 'T',
                'compliance_id' => NULL,
                'account_status' => 'A',
                'locked' => NULL,
                'base_account_no' => 'SW203'
            ],
            [
                'account_no' => 'SW209',
                'account_name' => 'BAYU PARIKESIT',
                'cif_no' => NULL,
                'asset_code' => 'IDR',
                'balance' => 0.00,
                'balance_hold' => NULL,
                'equiv_balance' => NULL,
                'account_type' => 'C',
                'is_base' => 'T',
                'compliance_id' => NULL,
                'account_status' => 'A',
                'locked' => NULL,
                'base_account_no' => 'SW209'
            ],
            [
                'account_no' => 'SW217',
                'account_name' => 'MAS BAGUS UNGGUL WISESA',
                'cif_no' => NULL,
                'asset_code' => 'IDR',
                'balance' => 0.00,
                'balance_hold' => NULL,
                'equiv_balance' => NULL,
                'account_type' => 'C',
                'is_base' => 'T',
                'compliance_id' => NULL,
                'account_status' => 'A',
                'locked' => NULL,
                'base_account_no' => 'SW217'
            ],
            [
                'account_no' => 'SW222',
                'account_name' => 'IKA PRISHANDANA',
                'cif_no' => NULL,
                'asset_code' => 'IDR',
                'balance' => 0.00,
                'balance_hold' => NULL,
                'equiv_balance' => NULL,
                'account_type' => 'C',
                'is_base' => 'T',
                'compliance_id' => NULL,
                'account_status' => 'A',
                'locked' => NULL,
                'base_account_no' => 'SW222'
            ],
            [
                'account_no' => 'SW242',
                'account_name' => 'HERLINA',
                'cif_no' => NULL,
                'asset_code' => 'IDR',
                'balance' => 0.00,
                'balance_hold' => NULL,
                'equiv_balance' => NULL,
                'account_type' => 'C',
                'is_base' => 'T',
                'compliance_id' => NULL,
                'account_status' => 'A',
                'locked' => NULL,
                'base_account_no' => 'SW242'
            ],
            [
                'account_no' => 'SW249',
                'account_name' => 'YUNI LAMPITA GULTOM',
                'cif_no' => NULL,
                'asset_code' => 'IDR',
                'balance' => 0.00,
                'balance_hold' => NULL,
                'equiv_balance' => NULL,
                'account_type' => 'C',
                'is_base' => 'T',
                'compliance_id' => NULL,
                'account_status' => 'A',
                'locked' => NULL,
                'base_account_no' => 'SW249'
            ],
            [
                'account_no' => 'SW251',
                'account_name' => 'SONY CHRISTIAN RUNTULALU',
                'cif_no' => NULL,
                'asset_code' => 'IDR',
                'balance' => 0.00,
                'balance_hold' => NULL,
                'equiv_balance' => NULL,
                'account_type' => 'C',
                'is_base' => 'T',
                'compliance_id' => NULL,
                'account_status' => 'A',
                'locked' => NULL,
                'base_account_no' => 'SW251'
            ],
            [
                'account_no' => 'SW256',
                'account_name' => 'TRINITA SITUMEANG',
                'cif_no' => NULL,
                'asset_code' => 'IDR',
                'balance' => 0.00,
                'balance_hold' => NULL,
                'equiv_balance' => NULL,
                'account_type' => 'C',
                'is_base' => 'T',
                'compliance_id' => NULL,
                'account_status' => 'A',
                'locked' => NULL,
                'base_account_no' => 'SW256'
            ],
            [
                'account_no' => 'SW263',
                'account_name' => 'GOUW THAY KWIE',
                'cif_no' => NULL,
                'asset_code' => 'IDR',
                'balance' => 0.00,
                'balance_hold' => NULL,
                'equiv_balance' => NULL,
                'account_type' => 'C',
                'is_base' => 'T',
                'compliance_id' => NULL,
                'account_status' => 'A',
                'locked' => NULL,
                'base_account_no' => 'SW263',
            ],
            [
                'account_no' => 'SW276',
                'account_name' => 'ICHWAN ZADELI',
                'cif_no' => NULL,
                'asset_code' => 'IDR',
                'balance' => 0.00,
                'balance_hold' => NULL,
                'equiv_balance' => NULL,
                'account_type' => 'C',
                'is_base' => 'T',
                'compliance_id' => NULL,
                'account_status' => 'A',
                'locked' => NULL,
                'base_account_no' => 'SW276'
            ],
        ];
        DB::table('account')->insert($arr);
    }
}
